# [blacklist/whitelist]
#   datetimelst = [{starttime, endtime, $header}...]
#
# datetimelst format: %Y-%m-%d %H:%M:%S
#
# support parameter:
#   none
#   all
#   $header

[blacklist]
datetimelst = [
    ["2023-03-01 00:01:03", "2023-03-01 00:01:04", "all"],
]

[whitelist]