[Global]
max_level = 1

[level_0]
boundary = { min = 0.0, max = 50.0 }

[level_1]
consist = [{interval = 1, unit = "min", difference = 1.0}]
errorflag = true

[[level_1.module]]
name = "helloworld"
module_type = "python"
path = "./module/hello_world.py"

[[level_1.module]]
name = "helloworld_2"
module_type = "python"
path = "./module/hello_world2.py"

